/bond_disable_heartbeat_timeout: true
FollowPath.allow_reversing: false
FollowPath.cost_scaling_dist: 0.6
FollowPath.cost_scaling_gain: 1.0
FollowPath.desired_linear_vel: 0.3
FollowPath.inflation_cost_scaling_factor: 3.0
FollowPath.lookahead_dist: 0.3
FollowPath.lookahead_time: 1.0
FollowPath.max_allowed_time_to_collision_up_to_carrot: 1.0
FollowPath.max_angular_accel: 2.0
FollowPath.max_lookahead_dist: 0.4
FollowPath.max_robot_pose_search_dist: 10.0
FollowPath.min_approach_linear_velocity: 0.05
FollowPath.min_lookahead_dist: 0.3
FollowPath.plugin: nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController
FollowPath.regulated_linear_scaling_min_radius: 0.9
FollowPath.regulated_linear_scaling_min_speed: 0.25
FollowPath.rotate_to_heading_angular_vel: 0.8
FollowPath.rotate_to_heading_min_angle: 0.785
FollowPath.transform_tolerance: 0.1
FollowPath.use_cost_regulated_linear_velocity_scaling: false
FollowPath.use_interpolation: false
FollowPath.use_regulated_linear_velocity_scaling: true
FollowPath.use_rotate_to_heading: true
FollowPath.use_velocity_scaled_lookahead_dist: false
controller_frequency: 20.0
controller_plugins:
- FollowPath
failure_tolerance: 0.0
goal_checker.plugin: nav2_controller::SimpleGoalChecker
goal_checker.stateful: true
goal_checker.xy_goal_tolerance: 0.15
goal_checker.yaw_goal_tolerance: 0.15
goal_checker_plugins:
- goal_checker
min_theta_velocity_threshold: 0.001
min_x_velocity_threshold: 0.001
min_y_velocity_threshold: 0.5
odom_topic: odom
progress_checker.movement_time_allowance: 2.0
progress_checker.plugin: nav2_controller::SimpleProgressChecker
progress_checker.required_movement_radius: 0.5
progress_checker_plugin: progress_checker
speed_limit_topic: speed_limit
use_sim_time: false
